name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen
          version: 1.0

      - name: Generate Docs
        run: make docs

  build-debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: external
          key: deps-${{ hashFiles('Makefile') }}

      - name: Download dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: make deps

      - name: Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc-arm-none-eabi ninja-build
          version: 1.0

      - name: APT Install Newlib headers
        run: sudo apt-get install -y libnewlib-arm-none-eabi

      - name: Build
        run: make release
