name: Release Build
run-name: ${{ github.actor }} performed ${{ github.event_name }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: external
          key: deps-${{ hashFiles('Makefile') }}

      - name: Download dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: make deps

      - name: Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc-arm-none-eabi libnewlib-arm-none-eabi ninja-build
          version: 1.0

      - name: Build
        run: make release
